name: demo-action

# on:
#   push:
#     branches: main
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - uses : actions/checkout@v4
        - name: run as sample job 
          run: echo "hello world!"

        - uses: Upload Artifect
        - name: actions/upload-artifact@v4
          with:
            name: build=artifact
            path: ${{github.workspace}}
           
          
