name: demo-action

on:
#   push:
#     branches: 
#       - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Run as sample job
        run: echo "hello world!"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}
  deploy:     
   runs-on: ubuntu-latest
    steps:    
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./downloaded-artifacts